Use op.dtype to create aten.empty.memory_format during decomposition. (#3941)
Prior to the change in this PR `torch-mlir-opt
--convert-torch-to-linalg` was running into the following error:

```
error: 'tensor.cast' op operand type 'tensor<200x200x26xf32>' and result type 'tensor<200x200x26xf64>' are cast incompatible
    %1 = torch.aten.empty.memory_format %0, %none, %none, %none, %false, %none : !torch.list<int>, !torch.none, !torch.none, !torch.none, !torch.bool, !torch.none -> !torch.vtensor<[200,200,26],f64>
         ^
note: see current operation: %12 = "tensor.cast"(%11) : (tensor<200x200x26xf32>) -> tensor<200x200x26xf64
```

This is because when `dtype` of the `aten.empty.memory_format` is
`none`, by default `f32` was being selected as the element type of the
resulting tensor which doesn't match with the actual element type of the
result.