Fix `torch-mlir-import-onnx` entry point
Due to the wrong entry point, calling `torch-mlir-import-onnx` currently
fails with
```
$ torch-mlir-import-onnx
Traceback (most recent call last):
  File "venv-torch/bin/torch-mlir-import-onnx", line 5, in <module>
    from torch_mlir.tools.import_onnx import _cli_main
ImportError: cannot import name '_cli_main' from 'torch_mlir.tools.import_onnx' (unknown location)
```